In [1]:
import numpy as np
import pandas as pd
#Regresion lineal multiple:


#regresores
x1=np.array([7,1,11,11,7,11,3,1,2,21,1,11,10])
x2=np.array([26,29,56,31,52,55,71,31,54,47,40,66,68])
x3=np.array([6,15,8,8,6,9,17,22,18,4,23,9,8])
x4=np.array([60,52,20,47,33,22,6,44,22,26,34,12,12])

#regresando
y=np.array([78.5,74.3,104.3,87.6,95.9,109.2,102.7,72.5,93.1,115.9,83.8,113.3,109.4])


data = {
    'x1': x1,
    'x2': x2,
    'x3': x3,
    'x4': x4,
    'y': y
}

#forma 

print(f'La forma de x1 es: {x1.shape}')
print(f'La forma de x2 es: {x2.shape}')
print(f'La forma de x3 es: {x3.shape}')
print(f'La forma de x4 es: {x4.shape}')
print(f'La forma de y es: {y.shape}')

La forma de x1 es: (13,)
La forma de x2 es: (13,)
La forma de x3 es: (13,)
La forma de x4 es: (13,)
La forma de y es: (13,)


In [2]:
# matriz X 
uno=np.ones(13)

X = np.column_stack((uno,x1, x2, x3, x4))

X

array([[ 1.,  7., 26.,  6., 60.],
       [ 1.,  1., 29., 15., 52.],
       [ 1., 11., 56.,  8., 20.],
       [ 1., 11., 31.,  8., 47.],
       [ 1.,  7., 52.,  6., 33.],
       [ 1., 11., 55.,  9., 22.],
       [ 1.,  3., 71., 17.,  6.],
       [ 1.,  1., 31., 22., 44.],
       [ 1.,  2., 54., 18., 22.],
       [ 1., 21., 47.,  4., 26.],
       [ 1.,  1., 40., 23., 34.],
       [ 1., 11., 66.,  9., 12.],
       [ 1., 10., 68.,  8., 12.]])

In [3]:
X.shape

(13, 5)

In [4]:
# Transpuesta

XT=X.T
XT


array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 7.,  1., 11., 11.,  7., 11.,  3.,  1.,  2., 21.,  1., 11., 10.],
       [26., 29., 56., 31., 52., 55., 71., 31., 54., 47., 40., 66., 68.],
       [ 6., 15.,  8.,  8.,  6.,  9., 17., 22., 18.,  4., 23.,  9.,  8.],
       [60., 52., 20., 47., 33., 22.,  6., 44., 22., 26., 34., 12., 12.]])

In [5]:
XT.shape

(5, 13)

In [6]:
#Multiplicacion 

mult=XT@X
mult
print(mult.shape)

(5, 5)


In [7]:
# funncion para validar si el determinando es dif de 0y corroborar que se puede realizar la operacion [X'X]-1

def es_determinante_no_cero(A, B):
 
    C = A@B
 
    determinante = np.linalg.det(C)
 
    return determinante != 0   #True si el determinante es diferente de 0, False en caso contrario

# si el det(A)=0 utilizar la inv de penrose-Moore
es_determinante_no_cero(XT,X)

True

In [8]:
# Inversa de la matriz [X'X]-1

inversa=A_inv = np.linalg.inv(mult)
inversa
inversa.shape

(5, 5)

In [9]:
#betas

b=inversa@XT@y
b
b.shape
b

array([62.4053693 ,  1.55110265,  0.51016758,  0.1019094 , -0.14406103])

In [10]:
#ecuacion de regrecion

def regresion_multiple(betas, matriz):
 
  y_hat = matriz@betas 
    
  return y_hat

In [11]:
prediccion=regresion_multiple(b,X)

In [20]:
df=pd.DataFrame(data)

df1=pd.DataFrame(prediccion)

df=pd.concat([df,df1],axis=1)
df.rename(columns={0:'Y_hat'},inplace=True)
df

x1  x2  x3  x4      y       Y_hat
0    7  26   6  60   78.5   78.495240
1    1  29  15  52   74.3   72.788799
2   11  56   8  20  104.3  105.970938
3   11  31   8  47   87.6   89.327100
4    7  52   6  33   95.9   95.649244
5   11  55   9  22  109.2  105.274557
6    3  71  17   6  102.7  104.148669
7    1  31  22  44   72.5   75.674989
8    2  54  18  22   93.1   91.721651
9   21  47   4  26  115.9  115.618452
10   1  40  23  34   83.8   81.809016
11  11  66   9  12  113.3  112.327011
12  10  68   8  12  109.4  111.694334

In [23]:
df['error'] = df['y'] - df['Y_hat']
df['error_cuadrado']=df['error']**2
df['error_cuadrado']=df['error']**2
sr = df['error_cuadrado'].sum()
df['error absoluto']=df['error_cuadrado'].abs()

print(f"El valor de Sr (suma de los residuos al cuadrado) es: {sr}")
df

El valor de Sr (suma de los residuos al cuadrado) es: 47.86363935049893


x1  x2  x3  x4      y       Y_hat     error  error_cuadrado  \
0    7  26   6  60   78.5   78.495240  0.004760        0.000023   
1    1  29  15  52   74.3   72.788799  1.511201        2.283728   
2   11  56   8  20  104.3  105.970938 -1.670938        2.792032   
3   11  31   8  47   87.6   89.327100 -1.727100        2.982875   
4    7  52   6  33   95.9   95.649244  0.250756        0.062878   
5   11  55   9  22  109.2  105.274557  3.925443       15.409100   
6    3  71  17   6  102.7  104.148669 -1.448669        2.098642   
7    1  31  22  44   72.5   75.674989 -3.174989       10.080552   
8    2  54  18  22   93.1   91.721651  1.378349        1.899847   
9   21  47   4  26  115.9  115.618452  0.281548        0.079269   
10   1  40  23  34   83.8   81.809016  1.990984        3.964016   
11  11  66   9  12  113.3  112.327011  0.972989        0.946708   
12  10  68   8  12  109.4  111.694334 -2.294334        5.263969   

    error absoluto  
0         0.000023  
1         2.283728  
2         2.792032  
3         2.982875  
4         0.062878  
5        15.409100  
6         2.098642  
7        10.080552  
8         1.899847  
9         0.079269  
10        3.964016  
11        0.946708  
12        5.263969

In [28]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, mean_squared_log_error

#  Error Cuadrático Medio 
def mse (sr,df):
    n=len(df)
    return sr/n

resultado_mse=mse(sr,df)

mse = mean_squared_error(df['y'], df['Y_hat'])

print(f'resultado del MSE propio :{resultado_mse} y con sklearn {mse}')


resultado del MSE propio :3.681818411576841 y con sklearn 3.681818411576841


In [29]:
#  Raíz del Error Cuadrático Medio  

def RMSE (mse):
    return mse ** 0.5

resultado_RMSE=RMSE(resultado_mse)
rmse = mean_squared_error(df['y'], df['Y_hat'], squared=False)

print(f'resultado del RMSE propio :{resultado_RMSE} y con sklearn {rmse}')

resultado del RMSE propio :1.918806507070695 y con sklearn 1.918806507070695


In [30]:
# Error Absoluto Medio  Calcular MAE


def MAE (df):
    n=len(df)
    mae=(df['error absoluto'].sum())/n
    return mae

resultado_mae=MAE(df)
mae = mean_absolute_error(df['y'], df['Y_hat'])
print(f'resultado del MAE propio :{resultado_mae} y con sklearn {mae}')


resultado del MAE propio :3.681818411576841 y con sklearn 1.5870814560524178


In [31]:
r2 = r2_score(df['y'], df['Y_hat'])
print(f"R^2: {r2}")

R^2: 0.9823756204076801
